language: ruby
cache: bundler
rvm:
- 2.0.0
env:
  matrix:
  - DB=postgresql
script:
- bundle exec rake db:test:prepare
- RAILS_ENV=test bundle exec rake spec
before_script:
- psql -c "CREATE USER \"baseline\" WITH PASSWORD 'notasecret';" -U postgres
- psql -c 'ALTER USER "baseline" CREATEDB;' -U postgres
- psql -c 'CREATE DATABASE "baseline-test"' -U postgres
- psql -c 'ALTER DATABASE "baseline-test" OWNER TO "baseline"' -U postgres
